#!/usr/bin/env bash
set -ex
cd "$(dirname "$0")/.."

# Clone only if the folder doesn't exist
if [[ ! -d "core" ]]; then
    git clone --depth 1 --branch dev https://github.com/home-assistant/core.git
fi

# Dev tools für C-Extensions
#sudo apt-get update && sudo apt-get install -y python3-dev build-essential gcc && sudo rm -rf /var/lib/apt/lists/*

# uv Package Manager installieren
pip install uv

pip install \
    colorlog \
    pip \
    ruff

# Optional: Clean up pip cache
pip cache purge


uv venv --clear --python 3.13
./scripts/setup-dependencies
./scripts/setup-symlinks
uv run pre-commit install-hooks
